unit 2
Zborovskii/java-super-course pull request #2
Opened 2020-01-27 20:42 UTC by Zborovskii

task1 - task3

2020-01-29 06:38 UTC, vadim-gleyf requested changes
разберись с maven
у тебя структура не правильная  - попробуй склонить проект с нуля и открыть идее как мейвен проект, модули не распознает
+ версию. жавки тоже попросит руками указать (укажи в помке_

2020-01-29 06:38 UTC, vadim-hleif commented on unit2/src/main/java/Task3/Pen.java
> +public class Pen extends Stationery{
форматирование

2020-01-29 06:38 UTC, vadim-hleif commented on unit2/src/main/java/Task3/Main.java
> +        List<Stationery> novichek = Arrays.asList(pen1, pen2, pen3, pencil1, pencil2);
сделай отдельный метод который возвращает набор новичка. (утилитный)

2020-01-29 06:38 UTC, vadim-hleif commented on unit2/src/main/java/Task3/Main.java
> +        Collections.sort(novichek, Comparator.comparing(Stationery::getPrice));
у листа есть метод сорт

2020-02-04 07:26 UTC, vadim-gleyf requested changes

2020-02-04 07:26 UTC, vadim-gleyf commented on unit2/src/main/java/task2/Main.java
> +        int summ = worker.getStationeries().stream().
в метод вынеси

2020-02-04 07:26 UTC, vadim-hleif commented on unit2/src/main/java/Task3/Main.java
> +package Task3;
имя пакета

обращай внимания на замечания идея + sonarlint поставь

2020-02-04 07:26 UTC, vadim-hleif commented on unit2/src/main/java/Task3/Main.java
> +        List<Stationery> novichek = createNovichek();
русские слова транслитом

2020-02-04 07:26 UTC, vadim-hleif commented on unit2/src/main/java/Task3/Main.java
> +        System.out.println(novichek);
выводит же все как stationery, поправь

2020-02-04 07:26 UTC, vadim-hleif commented on unit2/src/main/java/Task3/Pen.java
> +public class Pen extends Stationery{
ты не поправил

2020-02-04 07:26 UTC, vadim-hleif commented on unit2/src/main/java/task5/Student.java
> +    private HashMap<String, Double> marks;
оценки у студента double, перечитай условие

2020-02-04 07:26 UTC, vadim-hleif commented on unit2/src/main/java/task5/Main.java
> +        Subject math = new Subject("math", false);
ни на что же не влияет булеан твой

2020-02-04 07:26 UTC, vadim-hleif commented on unit2/src/main/java/task5/Main.java
> +        Subject math = new Subject("math", false);
могу везде вещественные пихать

2020-02-04 07:26 UTC, vadim-hleif commented on unit2/src/main/java/task5/Main.java
> +        studentsList.stream().
все агрегации выноси в статик методы

2020-02-04 07:26 UTC, vadim-hleif commented on unit2/src/main/java/task5/Main.java
> +                map(Student::getMarks).
форматирование странное,  точка обычно в начале строки, а не после

это жава а не го :)

2020-02-04 07:26 UTC, vadim-hleif commented on unit2/src/main/java/task6/Main.java
> +        NuclearSubmarin.SubmarinEngine submarinEngine = nuclearSubmarin.new SubmarinEngine();
явно при запуске лодки двигатель сам должен запускаться

типа создай инстанс двигателя в лодке

2020-02-04 19:53 UTC, Zborovskii commented on unit2/src/main/java/task5/Student.java
> +    private HashMap<String, Double> marks;
перечитал условие, сказано лишь про целые и вещественные оценки, не пойму почему нельзя использовать Double, и чем это плохо ?

2020-02-04 19:55 UTC, Zborovskii commented on unit2/src/main/java/task5/Student.java
> +    private HashMap<String, Double> marks;
К тому же примитив нельзя использовать в HashMap

2020-02-11 06:47 UTC, vadim-gleyf requested changes

2020-02-11 06:47 UTC, vadim-gleyf commented on unit2/src/main/java/ru/task5/Group.java
> +        newListOfMarks.addAll(marksList.get(student));
два раза гетаешь из мапы

2020-02-11 06:47 UTC, vadim-gleyf commented on unit2/src/main/java/ru/task5/Group.java
> +        newListOfMarks.addAll(marksList.get(student));
лист лишний создаешь и в него перекладываешь 

просто в тот добавляй

2020-02-11 06:47 UTC, vadim-gleyf commented on unit2/src/main/java/ru/task5/Group.java
> +        marksList.put(student, newListOfMarks);
не придется этот шаг тоже делать

2020-02-11 06:47 UTC, vadim-hleif commented on unit2/src/main/java/ru/task5/Group.java
> +        newListOfMarks.addAll(marksList.get(student));
@Zborovskii это не поравил

2020-02-13 06:55 UTC, vadim-gleyf requested changes

2020-02-13 06:55 UTC, vadim-hleif commented on unit2/src/main/java/ru/task5/Main.java
> +                .orElse(0.0);
как отличить кейс когда студента нет ни в одной группе и когда у него реально 0 средняя?

2020-02-13 07:04 UTC, Zborovskii commented on unit2/src/main/java/ru/task5/Main.java
> +                .orElse(0.0);
ну как вариант можно эксепшен кидать что такого студента нет в группе : (

2020-02-17 12:21 UTC, vadim-gleyf requested changes

2020-02-17 12:21 UTC, vadim-hleif commented on unit2/src/main/java/ru/task5/Main.java
> +                .orElse(0.0);
кидай

2020-02-19 07:10 UTC, vadim-gleyf approved these changes

2020-02-19 07:15 UTC, merged