unit 4 is done
Zborovskii/java-super-course pull request #4
Opened 2020-03-07 19:53 UTC by Zborovskii

2020-03-09 15:27 UTC, vadim-gleyf requested changes

2020-03-09 15:27 UTC, vadim-hleif commented on unit4/src/main/java/ru/task1task2/KeyWordsByteSearcher.java
> +            e.printStackTrace();
че за обработка

2020-03-09 15:27 UTC, vadim-hleif commented on unit4/src/main/java/ru/task1task2/KeyWordsService.java
> +    private static final String[] keyWordsArray = new String[]{
https://axis.apache.org/axis2/java/core/apidocs/org/apache/axis2/util/JavaUtils.html#isJavaKeyword-java.lang.String-

2020-03-10 06:16 UTC, Zborovskii commented on unit4/src/main/java/ru/task1task2/KeyWordsService.java
> +    private static final String[] keyWordsArray = new String[]{
https://github.com/wso2/wso2-axis2/blob/1d50b9c29e46b9c9a0e6d70f82e16db45b2ffb41/modules/kernel/src/org/apache/axis2/util/JavaUtils.java#L39
зачем что то подключать если реализация такая же

2020-03-10 13:59 UTC, vadim-hleif commented on unit4/src/main/java/ru/task1task2/KeyWordsService.java
> +    private static final String[] keyWordsArray = new String[]{
зачем что-то реализовывать если за тебя уже релизовали? + конфликт

2020-03-12 06:49 UTC, Zborovskii commented on unit4/src/main/java/ru/task1task2/KeyWordsByteSearcher.java
> +            System.out.println("Ошибка в ходе чтения исходного файла");
здесь поменял было e.printStackTrace

2020-03-12 06:49 UTC, Zborovskii commented on unit4/pom.xml
> +            <groupId>axis2</groupId>
добавил библиотеку в которой есть функция isKeyWord

2020-03-12 06:50 UTC, Zborovskii commented on unit4/src/main/java/ru/task1task2/KeyWordsByteSearcher.java
> +            System.out.println("Ошибка в ходе чтения исходного файла");
заменил ошибку e.printStackTrace

2020-03-12 06:52 UTC, Zborovskii commented on unit4/src/main/java/ru/task1task2/KeyWordsSearcher.java
> +                if (foundedKeyWords.containsKey(foundedWord)) {
раньше был отдельный сервис который определял является слово ключевым или нет, теперь смотрится через функцию библиотеки

2020-03-17 06:29 UTC, vadim-gleyf approved these changes

2020-03-17 09:53 UTC, merged